{
 "openapi": "3.0.1",
 "info": {
  "title": "PCB-GEO-TEST-PSD2-API",
  "description": "PCB-GEO-TEST-PSD2-API",
  "version": "v1",
  "x-logo": {
   "url": "https://www.procreditbank.ge/sites/default/files/main-logo.png"
  }
 },
 "servers": [
  {
   "url": "https://online-test.procreditbank.ge/0.8/v1"
  }
 ],
 "paths": {
  "/consents": {
   "post": {
    "tags": [
     "Consents"
    ],
    "summary": "01. Create consent",
    "operationId": "605a078404d6ce0d20a91b7d",
    "parameters": [
     {
      "name": "X-Request-ID",
      "in": "header",
      "description": "ID of the request, unique to the call, as determined by the initiating party.",
      "required": true,
      "schema": {
       "type": "string($uuid)"
      }
     },
     {
      "name": "x-jws-signature",
      "in": "header",
      "description": "A signature of the request by the TPP on application level.",
      "required": true,
      "schema": {
       "type": "string"
      }
     },
     {
      "name": "Digest",
      "in": "header",
      "description": "Is contained if and only if the \"x-jws-signature\" element is contained in the header of the request.",
      "required": true,
      "schema": {
       "type": "string"
      }
     },
     {
      "name": "PSU-IP-Address",
      "in": "header",
      "description": "The forwarded IP Address header field consists of the corresponding http request IP Address field between PSU and TPP. If not available, the TPP shall use the IP Address used by the TPP when submitting this request.",
      "required": true,
      "schema": {
       "type": "string($ipv4)"
      }
     }
    ],
    "requestBody": {
     "description": "Request body for a consents request.",
     "content": {
      "application/json": {
       "example": {
        "access": {
         "accounts": [],
         "balances": [],
         "transactions": []
        },
        "recurringIndicator": true,
        "validUntil": "2022-02-02",
        "frequencyPerDay": 4,
        "combinedServiceIndicator": true
       }
      }
     }
    },
    "responses": {
     "201": {
      "description": "",
      "content": {
       "application/json": {
        "example": {
         "consentStatus": "received",
         "consentId": "d02c9545-cfee-4b33-ae12-6dd4030e2252",
         "_links": {
          "scaOAuth": {
           "href": "https://tkn.24-7.ge/oauth/.well-known/configuration"
          },
          "self": {
           "href": "/0.8/v1/consents/d02c9545-cfee-4b33-ae12-6dd4030e2252"
          },
          "status": {
           "href": "/0.8/v1/consents/d02c9545-cfee-4b33-ae12-6dd4030e2252/status"
          }
         },
         "message": "Created"
        }
       }
      }
     },
     "400": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "401": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "403": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "404": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "405": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "406": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "408": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "415": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "429": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "500": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "503": {
      "description": "",
      "content": {
       "application/json": {}
      }
     }
    }
   }
  },
  "/consents/{consentId}": {
   "get": {
    "tags": [
     "Consents"
    ],
    "summary": "02. Get consent request",
    "operationId": "605a078504d6ce0d20a91b7e",
    "parameters": [
     {
      "name": "consentId",
      "in": "path",
      "description": "ID of the corresponding consent object as returned by an account information consent request.",
      "required": true,
      "schema": {
       "type": "string"
      }
     },
     {
      "name": "X-Request-ID",
      "in": "header",
      "description": "ID of the request, unique to the call, as determined by the initiating party.",
      "required": true,
      "schema": {
       "type": "string($uuid)"
      }
     },
     {
      "name": "x-jws-signature",
      "in": "header",
      "description": "A signature of the request by the TPP on application level.",
      "required": true,
      "schema": {
       "type": "string"
      }
     },
     {
      "name": "Digest",
      "in": "header",
      "description": "Is contained if and only if the \"x-jws-signature\" element is contained in the header of the request.",
      "required": true,
      "schema": {
       "type": "string"
      }
     },
     {
      "name": "PSU-IP-Address",
      "in": "header",
      "description": "The forwarded IP Address header field consists of the corresponding HTTP request IP Address field between PSU and TPP. It shall be contained if and only if this request was actively initiated by the PSU.",
      "schema": {
       "type": "string($ipv4)"
      }
     }
    ],
    "responses": {
     "200": {
      "description": "",
      "content": {
       "application/json": {
        "example": {
         "access": {
          "accounts": [
           {
            "iban": "GE38PC0133600100044650",
            "currency": "GEL"
           }
          ],
          "balances": [
           {
            "iban": "GE38PC0133600100044650",
            "currency": "GEL"
           }
          ],
          "transactions": [
           {
            "iban": "GE38PC0133600100044650",
            "currency": "GEL"
           }
          ]
         },
         "recurringIndicator": true,
         "validUntil": "2022-02-02",
         "frequencyPerDay": 4,
         "lastActionDate": "2021-11-11",
         "consentStatus": "valid"
        }
       }
      }
     },
     "400": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "401": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "403": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "404": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "405": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "406": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "408": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "415": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "429": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "500": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "503": {
      "description": "",
      "content": {
       "application/json": {}
      }
     }
    }
   },
   "delete": {
    "tags": [
     "Consents"
    ],
    "summary": "04. Delete consent",
    "operationId": "605a078504d6ce0d20a91b7f",
    "parameters": [
     {
      "name": "consentId",
      "in": "path",
      "description": "ID of the corresponding consent object as returned by an account information consent request.",
      "required": true,
      "schema": {
       "type": "string"
      }
     },
     {
      "name": "X-Request-ID",
      "in": "header",
      "description": "ID of the request, unique to the call, as determined by the initiating party.",
      "required": true,
      "schema": {
       "type": "string($uuid)"
      }
     },
     {
      "name": "x-jws-signature",
      "in": "header",
      "description": "A signature of the request by the TPP on application level.",
      "required": true,
      "schema": {
       "type": "string"
      }
     },
     {
      "name": "Digest",
      "in": "header",
      "description": "Is contained if and only if the \"x-jws-signature\" element is contained in the header of the request.",
      "required": true,
      "schema": {
       "type": "string"
      }
     },
     {
      "name": "PSU-IP-Address",
      "in": "header",
      "description": "The forwarded IP Address header field consists of the corresponding HTTP request IP Address field between PSU and TPP. It shall be contained if and only if this request was actively initiated by the PSU.",
      "schema": {
       "type": "string($ipv4)"
      }
     }
    ],
    "responses": {
     "204": {
      "description": "Success"
     },
     "400": {
      "description": ""
     },
     "401": {
      "description": ""
     },
     "403": {
      "description": ""
     },
     "404": {
      "description": ""
     },
     "405": {
      "description": ""
     },
     "406": {
      "description": ""
     },
     "408": {
      "description": ""
     },
     "415": {
      "description": ""
     },
     "429": {
      "description": ""
     },
     "500": {
      "description": ""
     },
     "503": {
      "description": ""
     }
    }
   }
  },
  "/consents/{consentId}/status": {
   "get": {
    "tags": [
     "Consents"
    ],
    "summary": "03. Consent status request",
    "operationId": "605a078504d6ce0d20a91b80",
    "parameters": [
     {
      "name": "consentId",
      "in": "path",
      "description": "ID of the corresponding consent object as returned by an account information consent request.",
      "required": true,
      "schema": {
       "type": "string"
      }
     },
     {
      "name": "X-Request-ID",
      "in": "header",
      "description": "ID of the request, unique to the call, as determined by the initiating party.",
      "required": true,
      "schema": {
       "type": "string($uuid)"
      }
     },
     {
      "name": "x-jws-signature",
      "in": "header",
      "description": "A signature of the request by the TPP on application level.",
      "required": true,
      "schema": {
       "type": "string"
      }
     },
     {
      "name": "Digest",
      "in": "header",
      "description": "Is contained if and only if the \"x-jws-signature\" element is contained in the header of the request.",
      "required": true,
      "schema": {
       "type": "string"
      }
     },
     {
      "name": "PSU-IP-Address",
      "in": "header",
      "description": "The forwarded IP Address header field consists of the corresponding HTTP request IP Address field between PSU and TPP. It shall be contained if and only if this request was actively initiated by the PSU.",
      "schema": {
       "type": "string($ipv4)"
      }
     }
    ],
    "responses": {
     "200": {
      "description": "",
      "content": {
       "application/json": {
        "example": {
         "consentStatus": "valid"
        }
       }
      }
     },
     "400": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "401": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "403": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "404": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "405": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "406": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "408": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "415": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "429": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "500": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "503": {
      "description": "",
      "content": {
       "application/json": {}
      }
     }
    }
   }
  },
  "/accounts": {
   "get": {
    "tags": [
     "Accounts"
    ],
    "summary": "05. Read account list",
    "operationId": "605a078504d6ce0d20a91b81",
    "parameters": [
     {
      "name": "withBalance",
      "in": "query",
      "description": "If contained, this function reads the list of accessible payment accounts including the booking balance,  if granted by the PSU in the related consent and available by the ASPSP.  This parameter might be ignored by the ASPSP.",
      "schema": {
       "type": "boolean"
      }
     },
     {
      "name": "X-Request-ID",
      "in": "header",
      "description": "ID of the request, unique to the call, as determined by the initiating party.",
      "required": true,
      "schema": {
       "type": "string($uuid)"
      }
     },
     {
      "name": "Consent-ID",
      "in": "header",
      "description": "This then contains the consentId of the related AIS consent.",
      "required": true,
      "schema": {
       "type": "string"
      }
     },
     {
      "name": "x-jws-signature",
      "in": "header",
      "description": "A signature of the request by the TPP on application level.",
      "required": true,
      "schema": {
       "type": "string"
      }
     },
     {
      "name": "Digest",
      "in": "header",
      "description": "Is contained if and only if the \"x-jws-signature\" element is contained in the header of the request.",
      "required": true,
      "schema": {
       "type": "string"
      }
     },
     {
      "name": "PSU-IP-Address",
      "in": "header",
      "description": "The forwarded IP Address header field consists of the corresponding HTTP request IP Address field between PSU and TPP. It shall be contained if and only if this request was actively initiated by the PSU.",
      "schema": {
       "type": "string($ipv4)"
      }
     }
    ],
    "responses": {
     "200": {
      "description": "",
      "content": {
       "application/json": {
        "example": {
         "accounts": [
          {
           "resourceId": "16653013",
           "iban": "GE38PC0133600100044650",
           "currency": "GEL",
           "name": "GE38PC0133600100044650",
           "product": "მიმდინარე ანგარიში",
           "status": "enabled",
           "bic": "MIBGGE22",
           "balances": [],
           "_links": {
            "balances": {
             "href": "/0.8/v1/accounts/16653013/balances"
            },
            "transactions": {
             "href": "/0.8/v1/accounts/16653013/transactions"
            }
           }
          }
         ]
        }
       }
      }
     },
     "400": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "401": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "403": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "404": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "405": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "406": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "408": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "415": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "429": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "500": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "503": {
      "description": "",
      "content": {
       "application/json": {}
      }
     }
    }
   }
  },
  "/accounts/{account-id}/balances": {
   "get": {
    "tags": [
     "Accounts"
    ],
    "summary": "07. Read balance",
    "operationId": "605a078504d6ce0d20a91b82",
    "parameters": [
     {
      "name": "account-id",
      "in": "path",
      "description": "This identification is denoting the addressed account. The account-id is retrieved by using a \"Read Account List\" call. The account-id is the \"resourceId\" attribute of the account structure. Its value is constant at least throughout the lifecycle of a given consent.",
      "required": true,
      "schema": {
       "type": "string"
      }
     },
     {
      "name": "X-Request-ID",
      "in": "header",
      "description": "ID of the request, unique to the call, as determined by the initiating party.",
      "required": true,
      "schema": {
       "type": "string($uuid)"
      }
     },
     {
      "name": "Consent-ID",
      "in": "header",
      "description": "This then contains the consentId of the related AIS consent.",
      "required": true,
      "schema": {
       "type": "string"
      }
     },
     {
      "name": "x-jws-signature",
      "in": "header",
      "description": "A signature of the request by the TPP on application level.",
      "required": true,
      "schema": {
       "type": "string"
      }
     },
     {
      "name": "Digest",
      "in": "header",
      "description": "Is contained if and only if the \"x-jws-signature\" element is contained in the header of the request.",
      "required": true,
      "schema": {
       "type": "string"
      }
     },
     {
      "name": "PSU-IP-Address",
      "in": "header",
      "description": "The forwarded IP Address header field consists of the corresponding HTTP request IP Address field between PSU and TPP. It shall be contained if and only if this request was actively initiated by the PSU.",
      "schema": {
       "type": "string($ipv4)"
      }
     }
    ],
    "responses": {
     "200": {
      "description": "",
      "content": {
       "application/json": {
        "example": {
         "account": {
          "iban": "GE38PC0133600100044650",
          "currency": "GEL"
         },
         "balances": [
          {
           "balanceAmount": {
            "currency": "GEL",
            "amount": 101.5
           },
           "balanceType": "interimAvailable"
          },
          {
           "balanceAmount": {
            "currency": "GEL",
            "amount": 101.5
           },
           "balanceType": "closingBooked"
          }
         ]
        }
       }
      }
     },
     "400": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "401": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "403": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "404": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "405": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "406": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "408": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "415": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "429": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "500": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "503": {
      "description": "",
      "content": {
       "application/json": {}
      }
     }
    }
   }
  },
  "/accounts/{account-id}": {
   "get": {
    "tags": [
     "Accounts"
    ],
    "summary": "06. Read account details",
    "operationId": "605a078504d6ce0d20a91b83",
    "parameters": [
     {
      "name": "account-id",
      "in": "path",
      "description": "This identification is denoting the addressed account. The account-id is retrieved by using a \"Read Account List\" call. The account-id is the \"resourceId\" attribute of the account structure. Its value is constant at least throughout the lifecycle of a given consent.",
      "required": true,
      "schema": {
       "type": "string"
      }
     },
     {
      "name": "withBalance",
      "in": "query",
      "description": "If contained, this function reads the list of accessible payment accounts including the booking balance,  if granted by the PSU in the related consent and available by the ASPSP.  This parameter might be ignored by the ASPSP.",
      "schema": {
       "type": "boolean"
      }
     },
     {
      "name": "X-Request-ID",
      "in": "header",
      "description": "ID of the request, unique to the call, as determined by the initiating party.",
      "required": true,
      "schema": {
       "type": "string($uuid)"
      }
     },
     {
      "name": "Consent-ID",
      "in": "header",
      "description": "This then contains the consentId of the related AIS consent.",
      "required": true,
      "schema": {
       "type": "string"
      }
     },
     {
      "name": "x-jws-signature",
      "in": "header",
      "description": "A signature of the request by the TPP on application level.",
      "required": true,
      "schema": {
       "type": "string"
      }
     },
     {
      "name": "Digest",
      "in": "header",
      "description": "Is contained if and only if the \"x-jws-signature\" element is contained in the header of the request.",
      "required": true,
      "schema": {
       "type": "string"
      }
     },
     {
      "name": "PSU-IP-Address",
      "in": "header",
      "description": "The forwarded IP Address header field consists of the corresponding HTTP request IP Address field between PSU and TPP. It shall be contained if and only if this request was actively initiated by the PSU.",
      "schema": {
       "type": "string($ipv4)"
      }
     }
    ],
    "responses": {
     "200": {
      "description": "",
      "content": {
       "application/json": {
        "example": {
         "account": {
          "resourceId": "16653013",
          "iban": "GE38PC0133600100044650",
          "currency": "GEL",
          "name": "GE38PC0133600100044650",
          "product": "მიმდინარე ანგარიში",
          "status": "enabled",
          "bic": "MIBGGE22",
          "balances": [],
          "_links": {
           "balances": {
            "href": "/0.8/v1/accounts/16653013/balances"
           },
           "transactions": {
            "href": "/0.8/v1/accounts/16653013/transactions"
           }
          }
         }
        }
       }
      }
     },
     "400": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "401": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "403": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "404": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "405": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "406": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "408": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "415": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "429": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "500": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "503": {
      "description": "",
      "content": {
       "application/json": {}
      }
     }
    }
   }
  },
  "/accounts/{account-id}/transactions": {
   "get": {
    "tags": [
     "Accounts"
    ],
    "summary": "08. Read transaction list of an account",
    "operationId": "605a078504d6ce0d20a91b84",
    "parameters": [
     {
      "name": "account-id",
      "in": "path",
      "description": "This identification is denoting the addressed account. The account-id is retrieved by using a \"Read Account List\" call. The account-id is the \"resourceId\" attribute of the account structure. Its value is constant at least throughout the lifecycle of a given consent.",
      "required": true,
      "schema": {
       "type": "string"
      }
     },
     {
      "name": "withBalance",
      "in": "query",
      "description": "If contained, this function reads the list of accessible payment accounts including the booking balance,  if granted by the PSU in the related consent and available by the ASPSP.  This parameter might be ignored by the ASPSP.",
      "schema": {
       "type": "boolean"
      }
     },
     {
      "name": "entryReferenceFrom",
      "in": "query",
      "description": "This data attribute is indicating that the AISP is in favour to get all transactions after the transaction with identification entryReferenceFrom alternatively to the above defined period.",
      "schema": {
       "type": "string"
      }
     },
     {
      "name": "dateFrom",
      "in": "query",
      "schema": {
       "type": "string($date)"
      }
     },
     {
      "name": "dateTo",
      "in": "query",
      "schema": {
       "type": "string($date)"
      }
     },
     {
      "name": "bookingStatus",
      "in": "query",
      "description": "Available values : booked, pending, both",
      "required": true,
      "schema": {
       "type": "string"
      }
     },
     {
      "name": "X-Request-ID",
      "in": "header",
      "description": "ID of the request, unique to the call, as determined by the initiating party.",
      "required": true,
      "schema": {
       "type": "string($uuid)"
      }
     },
     {
      "name": "Consent-ID",
      "in": "header",
      "description": "This then contains the consentId of the related AIS consent.",
      "required": true,
      "schema": {
       "type": "string"
      }
     },
     {
      "name": "x-jws-signature",
      "in": "header",
      "description": "A signature of the request by the TPP on application level.",
      "required": true,
      "schema": {
       "type": "string"
      }
     },
     {
      "name": "Digest",
      "in": "header",
      "description": "Is contained if and only if the \"x-jws-signature\" element is contained in the header of the request.",
      "required": true,
      "schema": {
       "type": "string"
      }
     },
     {
      "name": "PSU-IP-Address",
      "in": "header",
      "description": "The forwarded IP Address header field consists of the corresponding HTTP request IP Address field between PSU and TPP. It shall be contained if and only if this request was actively initiated by the PSU.",
      "schema": {
       "type": "string($ipv4)"
      }
     }
    ],
    "responses": {
     "200": {
      "description": "",
      "content": {
       "application/json": {
        "example": {
         "account": {
          "iban": "GE38PC0133600100044650",
          "currency": "GEL"
         },
         "transactions": {
          "booked": [
           {
            "entryReference": "1104978161",
            "bookingDate": "2021-04-06",
            "valueDate": "2021-04-06",
            "transactionAmount": {
             "currency": "GEL",
             "amount": 27.6
            },
            "creditorName": "Jioevi Veronika",
            "creditorAccount": {
             "iban": "GE38PC0133600100044650"
            },
            "remittanceInformationUnstructured": "ყიდვა/Purchase via POS terminal, 27.6 GEL, MARIAMI MAISURADZE I, MARIAMI MAISURADZE I/E   TBILISI      GE, 417435******6229, 04/04/2021 13:11:03.-."
           },
           {
            "entryReference": "1104974652",
            "bookingDate": "2021-04-06",
            "valueDate": "2021-04-06",
            "transactionAmount": {
             "currency": "GEL",
             "amount": 150
            },
            "creditorName": "ფარეიშვილი ნოდარ",
            "creditorAccount": {
             "iban": "GE07PC0133600400004128"
            },
            "remittanceInformationUnstructured": "ნაშთის გადატანა.ნაშთის გადატანა."
           }
          ],
          "_links": {
           "account": {
            "href": "/0.8/v1/accounts/16653013"
           },
           "first": {
            "href": "/0.8/v1/accounts/16653013/transactions?bookingStatus=booked&dateFrom=2021-04-06&dateTo=2021-04-07"
           }
          }
         }
        }
       }
      }
     },
     "400": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "401": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "403": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "404": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "405": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "406": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "408": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "415": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "429": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "500": {
      "description": "",
      "content": {
       "application/json": {}
      }
     },
     "503": {
      "description": "",
      "content": {
       "application/json": {}
      }
     }
    }
   }
  },
  "/{payment-service}/{payment-product}": {
   "post": {
    "tags": [
     "Payments"
    ],
    "summary": "09. Payment initiation request",
    "operationId": "09-payment-initiation-request",
    "parameters": [
     {
      "name": "payment-service",
      "in": "path",
      "description": "There are the following payment services:\n- payments\n- bulk-payments",
      "required": true,
      "schema": {
       "enum": [
        "payments",
        "bulk-payments"
       ],
       "type": "string"
      }
     },
     {
      "name": "payment-product",
      "in": "path",
      "description": "The following payment products are supported:\n- domestic\n- foreign",
      "required": true,
      "schema": {
       "enum": [
        "domestic",
        "foreign"
       ],
       "type": "string"
      }
     },
     {
      "name": "X-Request-ID",
      "in": "header",
      "description": "ID of the request, unique to the call, as determined by the initiating party.",
      "required": true,
      "schema": {
       "type": "string($uuid)"
      }
     },
     {
      "name": "x-jws-signature",
      "in": "header",
      "description": "A signature of the request by the TPP on application level.",
      "required": true,
      "schema": {
       "type": "string"
      }
     },
     {
      "name": "Digest",
      "in": "header",
      "description": "Is contained if and only if the \"x-jws-signature\" element is contained in the header of the request.",
      "required": true,
      "schema": {
       "type": "string"
      }
     },
     {
      "name": "PSU-IP-Address",
      "in": "header",
      "description": "The forwarded IP Address header field consists of the corresponding http request IP Address field between PSU and TPP. If not available, the TPP shall use the IP Address used by the TPP when submitting this request.",
      "required": true,
      "schema": {
       "type": "string($ipv4)"
      }
     },
     {
      "name": "TPP-Rejection-NoFunds-Preferred",
      "in": "header",
      "description": "If it equals \"true\" then the TPP prefers a rejection of the payment initiation in case the ASPSP is providing an integrated confirmation of funds request an the result of this is that not sufficient funds are available.\n\nIf it equals \"false\" then the TPP prefers that the ASPSP is dealing with the payment initiation like in the ASPSPs online channel, potentially waiting for a certain time period for funds to arrive to initiate the payment.",
      "schema": {
       "type": "boolean"
      }
     }
    ],
    "requestBody": {
     "description": "JSON request body for a payment inition request message.",
     "content": {
      "application/json": {
       "example": {
        "creditorAccount": {
         "iban": "GE07PC0133600400004128",
         "currency": ""
        },
        "creditorName": "domestic",
        "remittanceInformationUnstructured": "domestic",
        "debtorAccount": {
         "iban": "GE38PC0133600100044650",
         "currency": ""
        },
        "instructedAmount": {
         "currency": "GEL",
         "value": 9.99
        }
       }
      }
     }
    },
    "responses": {
     "201": {
      "description": "",
      "content": {
       "application/json": {
        "example": {
         "transactionStatus": "ACCC",
         "paymentId": "d712c168-4df2-4674-a7c7-a8da7ec52b63",
         "_links": {
          "self": {
           "href": "/0.8/v1/payments/domestic/d712c168-4df2-4674-a7c7-a8da7ec52b63"
          },
          "status": {
           "href": "/0.8/v1/payments/domestic/d712c168-4df2-4674-a7c7-a8da7ec52b63/status"
          }
         },
         "psuMessage": "Login to e-Banking"
        }
       }
      }
     },
     "400": {
      "description": ""
     },
     "401": {
      "description": ""
     },
     "403": {
      "description": ""
     },
     "404": {
      "description": ""
     },
     "405": {
      "description": ""
     },
     "406": {
      "description": ""
     },
     "408": {
      "description": ""
     },
     "409": {
      "description": ""
     },
     "415": {
      "description": ""
     },
     "429": {
      "description": ""
     },
     "500": {
      "description": ""
     },
     "503": {
      "description": ""
     }
    }
   }
  },
  "/{payment-service}/{payment-product}/{paymentId}/status": {
   "get": {
    "tags": [
     "Payments"
    ],
    "summary": "11. Payment initiation status request",
    "operationId": "payment-initiation-status-request",
    "parameters": [
     {
      "name": "payment-service",
      "in": "path",
      "description": "There are the following payment services:\n- payments\n- bulk-payments",
      "required": true,
      "schema": {
       "enum": [
        "payments",
        "bulk-payments"
       ],
       "type": "string"
      }
     },
     {
      "name": "payment-product",
      "in": "path",
      "description": "The following payment products are supported:\n- domestic\n- foreign",
      "required": true,
      "schema": {
       "enum": [
        "domestic",
        "foreign"
       ],
       "type": "string"
      }
     },
     {
      "name": "paymentId",
      "in": "path",
      "description": "Resource identification of the generated payment initiation resource.",
      "required": true,
      "schema": {
       "type": "string"
      }
     },
     {
      "name": "X-Request-ID",
      "in": "header",
      "description": "ID of the request, unique to the call, as determined by the initiating party.",
      "required": true,
      "schema": {
       "type": "string($uuid)"
      }
     },
     {
      "name": "x-jws-signature",
      "in": "header",
      "description": "A signature of the request by the TPP on application level.",
      "required": true,
      "schema": {
       "type": "string"
      }
     },
     {
      "name": "Digest",
      "in": "header",
      "description": "Is contained if and only if the \"x-jws-signature\" element is contained in the header of the request.",
      "required": true,
      "schema": {
       "type": "string"
      }
     }
    ],
    "responses": {
     "200": {
      "description": "",
      "content": {
       "application/json": {
        "example": {
         "transactionStatus": "ACCC"
        }
       }
      }
     }
    }
   }
  },
  "/{payment-service}/{payment-product}/{paymentId}": {
   "get": {
    "tags": [
     "Payments"
    ],
    "summary": "10. Get payment information",
    "operationId": "get-payment-information",
    "parameters": [
     {
      "name": "payment-service",
      "in": "path",
      "description": "There are the following payment services:\n- payments\n- bulk-payments",
      "required": true,
      "schema": {
       "enum": [
        "payments",
        "bulk-payments"
       ],
       "type": "string"
      }
     },
     {
      "name": "payment-product",
      "in": "path",
      "description": "The following payment products are supported:\n- domestic\n- foreign",
      "required": true,
      "schema": {
       "enum": [
        "domestic",
        "foreign"
       ],
       "type": "string"
      }
     },
     {
      "name": "paymentId",
      "in": "path",
      "description": "Resource identification of the generated payment initiation resource.",
      "required": true,
      "schema": {
       "type": "string"
      }
     },
     {
      "name": "X-Request-ID",
      "in": "header",
      "description": "ID of the request, unique to the call, as determined by the initiating party.",
      "required": true,
      "schema": {
       "type": "string($uuid)"
      }
     },
     {
      "name": "x-jws-signature",
      "in": "header",
      "description": "A signature of the request by the TPP on application level.",
      "required": true,
      "schema": {
       "type": "string"
      }
     },
     {
      "name": "Digest",
      "in": "header",
      "description": "Is contained if and only if the \"x-jws-signature\" element is contained in the header of the request.",
      "required": true,
      "schema": {
       "type": "string"
      }
     }
    ],
    "responses": {
     "200": {
      "description": "",
      "content": {
       "application/json": {
        "example": {
         "debtorAccount": {
          "currency": "GEL"
         },
         "debtorIdentification": {
          "privateId": {
           "others": [
            {
             "identification": "PNOGE-01019016022"
            }
           ]
          }
         },
         "instructedAmount": {
          "currency": "GEL",
          "amount": 100
         },
         "creditorAccount": {
          "iban": "GE08PC0003600400000813",
          "currency": "GEL"
         },
         "creditorAgent": "MIBGGE22",
         "creditorName": "ფარეიშვილი ნოდარ",
         "creditorIdentification": {
          "privateId": {
           "others": [
            {
             "identification": "PNOGE-01019016022"
            }
           ]
          }
         },
         "chargeBearer": "DEBT",
         "remittanceInformationUnstructured": "საკუთარ ანგარიშებს შორის გადარიცხვა",
         "remittanceInformationUnstructuredArray": [],
         "instructionPriority": "HIGH",
         "transactionStatus": "RCVD"
        }
       }
      }
     }
    }
   },
   "delete": {
    "tags": [
     "Payments"
    ],
    "summary": "12. Payment cancellation request",
    "operationId": "payment-cancellation-request",
    "parameters": [
     {
      "name": "payment-service",
      "in": "path",
      "description": "There are the following payment services:\n- payments\n- bulk-payments",
      "required": true,
      "schema": {
       "enum": [
        "payments",
        "bulk-payments"
       ],
       "type": "string"
      }
     },
     {
      "name": "payment-product",
      "in": "path",
      "description": "The following payment products are supported:\n- domestic\n- foreign",
      "required": true,
      "schema": {
       "enum": [
        "domestic",
        "foreign"
       ],
       "type": "string"
      }
     },
     {
      "name": "paymentId",
      "in": "path",
      "description": "Resource identification of the generated payment initiation resource.",
      "required": true,
      "schema": {
       "type": "string"
      }
     },
     {
      "name": "X-Request-ID",
      "in": "header",
      "description": "ID of the request, unique to the call, as determined by the initiating party.",
      "required": true,
      "schema": {
       "type": "string($uuid)"
      }
     },
     {
      "name": "x-jws-signature",
      "in": "header",
      "description": "A signature of the request by the TPP on application level.",
      "required": true,
      "schema": {
       "type": "string"
      }
     },
     {
      "name": "Digest",
      "in": "header",
      "description": "Is contained if and only if the \"x-jws-signature\" element is contained in the header of the request.",
      "required": true,
      "schema": {
       "type": "string"
      }
     },
     {
      "name": "PSU-IP-Address",
      "in": "header",
      "description": "The forwarded IP Address header field consists of the corresponding http request IP Address field between PSU and TPP.",
      "schema": {
       "type": "string($ipv4)"
      }
     }
    ],
    "responses": {
     "204": {
      "description": "Success"
     }
    }
   }
  }
 },
 "components": {
  "securitySchemes": {
   "apiKeyHeader": {
    "type": "apiKey",
    "name": "Ocp-Apim-Subscription-Key",
    "in": "header"
   },
   "apiKeyQuery": {
    "type": "apiKey",
    "name": "subscription-key",
    "in": "query"
   }
  }
 },
 "security": [
  {
   "apiKeyHeader": []
  },
  {
   "apiKeyQuery": []
  }
 ]
}